# REQUIRED INPUTS
DATA_DIR: "test/data"
SUMSTATS_DIR: "test/data/sumstats"
OUTPUTS_DIR: "test/outputs"

# PARAMETER LIST
DISTANCE_LIMIT: 250000

DENSE_NVAR_THRESHOLD: 500
SIGNAL_DROPOUT_THRESHOLD: 0.1
COLOC_H4_THRESHOLD: 0.75
SENSITIVITY_P12_THRESHOLD: 1e-6