###############################################################################
###############################################################################

# REQUIRED INPUTS, ADJUST AS NEEDED

# Directories for input data, summary statistics, and outputs
# Input data directory should include a file "input_signals.csv" with columns:

# chromosome, position, gwas, allele1, allele2, pval, type, scalar

# gwas should indicate the prefix of the summary statistics file for that signal
# type should be either "cc" or "quant"
# scalar should be the case fraction for cc traits, or standard deviation for quant traits
# for quant traits, this is usually normalized to 1

DATA_DIR: "../test/data"
SUMSTATS_DIR: "../test/data/sumstats"
OUTPUTS_DIR: "../test/outputs"

###############################################################################
###############################################################################

# ADJUSTABLE PARAMETERS

# Max distance between signals to consider for colocalization
DISTANCE_LIMIT: 250000

# Colocalization filtering thresholds
DENSE_NVAR_THRESHOLD: 500
SIGNAL_DROPOUT_THRESHOLD: 0.1
COLOC_H4_THRESHOLD: 0.75
SENSITIVITY_P12_THRESHOLD: 1e-6

# Colocalization calling criteria
MIN_N: 2  # require both AB/BA analyses to be present
MIN_DENSE: 1  # at least one analysis must be dense
MAX_DROPOUT: 0  # no analyses can have signal dropout
MIN_COLOC: 2  # both analyses must show strong support for colocalization
MIN_ROBUST: 1  # at least one analysis must be robust to many priors